insert into SUB_CATEGORIES (ID,NAME)VALUES ( 1,'Sushi' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 2,'Pizza' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 3,'Burgery' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 4,'Chińczyk' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 5,'Hindus' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 6,'Owoce Morza' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 7,'Kebab' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 8,'Spozywcze' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 9,'meblowy' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 10,'budowlany' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 11,'sportowy' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 12,'ksiazki' );
insert into SUB_CATEGORIES (ID,NAME)VALUES ( 13,'dekoracje' );

insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (1,'adres1','imie1','nazwisko1',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description1',1);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (2,'adres2','imie2','nazwisko2',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description2',2);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (3,'adres3','imie3','nazwisko3',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description3',3);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (4,'adres4','imie4','nazwisko4',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description4',4);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (5,'adres5','imie5','nazwisko5',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description5',5);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (6,'adres6','imie6','nazwisko6',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description6',6);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (7,'adres7','imie7','nazwisko7',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description7',7);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (8,'adres8','imie8','nazwisko8',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description8',8);
insert into ORDERS (ID,CONSUMENT_ADRESS,CONSUMENT_NAME,CONSUMENT_SURNAME,DELIVERY_TIME,DESCRIPTION,PRICE) VALUES (9,'adres9','imie9','nazwisko9',parsedatetime('17-09-2012 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),'description9',9);

insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(1,'opis1','nazwa1',1, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(2,'opis2','nazwa2',2, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(3,'opis3','nazwa3',3, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(4,'opis4','nazwa4',4, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(5,'opis5','nazwa5',5, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(6,'opis6','nazwa6',6, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(7,'opis7','nazwa7',7, NULL);
insert into PRODUCT (ID,DESCRIPTION,NAME,PRICE,PRODUCT_PICTURE) VALUES(8,'opis8','nazwa8',8, NULL);

insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 1 , 8296711906841661984, 'losowa ulica1', 'losowy opis1', 'email@email1', 'nazwa firmy1', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 2 , 8296711906841661984, 'losowa ulica2', 'losowy opis2', 'email@email2', 'nazwa firmy2', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 3 , 8296711906841661984, 'losowa ulica3', 'losowy opis3', 'email@email3', 'nazwa firmy3', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 4 , 8296711906841661984, 'losowa ulica4', 'losowy opis4', 'email@email4', 'nazwa firmy4', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 5 , 8296711906841661984, 'losowa ulica5', 'losowy opis5', 'email@email5', 'nazwa firmy5', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 6 , 8296711906841661984, 'losowa ulica6', 'losowy opis6', 'email@email6', 'nazwa firmy6', 6250680088, 332979093, NULL, NULL );
insert into BUSINESS (ID,ACCOUNT_NUMBER,ADRESSS,DESCRIPTION,EMAIL,NAME,NIP,PHONE_NUMBER,STORE_PICTURE,CATEGORY_ID) VALUES( 7 , 8296711906841661984, 'losowa ulica7', 'losowy opis7', 'email@email7', 'nazwa firmy7', 6250680088, 332979093, NULL, NULL );

insert into FOOD_PRODUCT (ID,PRODUCT_ID)VALUES(1,NULL);
insert into FOOD_PRODUCT (ID,PRODUCT_ID)VALUES(2,NULL);
insert into FOOD_PRODUCT (ID,PRODUCT_ID)VALUES(3,NULL);
insert into FOOD_PRODUCT (ID,PRODUCT_ID)VALUES(4,NULL);
insert into FOOD_PRODUCT (ID,PRODUCT_ID)VALUES(5,NULL);

insert into RETAIL_PRODUCT (ID,NUMBER_OF_ITEMS,PRODUCT_ID)VALUES(1,1,NULL);
insert into RETAIL_PRODUCT (ID,NUMBER_OF_ITEMS,PRODUCT_ID)VALUES(2,2,NULL);
insert into RETAIL_PRODUCT (ID,NUMBER_OF_ITEMS,PRODUCT_ID)VALUES(3,3,NULL);
insert into RETAIL_PRODUCT (ID,NUMBER_OF_ITEMS,PRODUCT_ID)VALUES(4,4,NULL);

insert into BUSINESS_CATEGORY(ID,NAME) VALUES (1, 'Jedzenie');
insert into BUSINESS_CATEGORY(ID,NAME) VALUES (2, 'Usługi');
insert into BUSINESS_CATEGORY(ID,NAME) VALUES (3, 'Zakupy');
